### ISSUE TITLE
Check domains via IP address

### ISSUE THREAD

**Issue by dcarriger** [micke/valid_email2#109]
There's already an open issue to check for the domain via MX records, but it would also be useful to resolve those to the IP address and check that against a list. For example, matamuasu.cf is on the list and resolves to 213.32.90.201. That mail server will accept mail for all domains, however, and in the last 24 hours I've seen mail destined to 890 other domains at that same IP (I work at a midsize ESP). Adding every new domain to the list that starts pointing to that IP address will get very unwieldy, very quickly.

**Comment by lisinge** [comment]
It's a nice idea but i think it will become slow and problematic to resolve all the domains in the list and then keep them up-to-date to be able to match against them.

**Comment by micke** [comment]
Closing this. It's a good idea but i can't see any way of doing this without it being too slow.
