### ISSUE TITLE
Many known disposable providers are not present into list

### ISSUE THREAD

**Issue by diegodurante** [micke/valid_email2#115]
Would be great to be aligned with also [this json](https://github.com/ivolo/disposable-email-domains/blob/master/index.json) as I can see some domains listed there and not in valid_email2 gem.

For example: 
- daciasandero.tk
- lg-g7.tk
- one2mail.info
- emailure.net
- uemail99.com
- yopmail.ml
- mailsac.tk
... and more!

**Comment by lisinge** [comment]
The fastest way is usually to open a PR with the missing domains added.

I try my best to accept PRs in a timely manner and usually cuts a new release the same day of i have time

**Comment by micke** [comment]
Fixed in #122
