### ISSUE TITLE
ArgumentError (Unknown validator: 'ValidEmail2::EmailValidator')

### ISSUE THREAD

**Issue by cdhagmann** [micke/valid_email2#121]
When trying to create a object that contains a validated email it fails to create the object due to the above error.

**Comment by micke** [comment]
@cdhagmann Could you please post your Gemfile.lock?
You must be using a old version or you haven't properly bundled the gem.

**Comment by micke** [comment]
@dhanson358 You don't happen to have a Gemfile and a model to show me where you are having this error?

**Comment by micke** [comment]
@cdhagmann @dhanson358 I just generated a new Rails app using the following commands:
1. `gem install rails`
2. `rails new tester`
3. `cd tester`
4. `echo 'gem "valid_email2"' >> Gemfile`
5. `bundle`
6. `rails g model user email:string`
7. In `app/models/user.rb`:
```ruby
validates :email, 'valid_email_2/email': { mx: true, disposable: true, disallow_subaddressing: true}
```
8. `rails c`

```ruby
irb(main):004:0> user = User.new(email: "test@asdasdafoifsidf.com")
=> #<User id: nil, email: "test@asdasdafoifsidf.com", created_at: nil, updated_at: nil>
irb(main):005:0> user.save
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
=> false
irb(main):006:0> user.errors
=> #<ActiveModel::Errors:0x00007fa2a635d6f8 @base=#<User id: nil, email: "test@asdasdafoifsidf.com", created_at: nil, updated_at: nil>, @messages={:email=>["is invalid"]}, @details={:email=>[{:error=>:invalid}]}>
```

You must have missed something in your apps.
I'm closing this issue as i can't replicate you errors locally.
Feel free to comment if you can supply me with a app where i can replicate this issue.

**Comment by dhanson358** [comment]
This may be something to do with the interaction of this gem and devise-security gem.  They recommend this gem in their README (which is how I found it).  Check out this app:

https://github.com/dhanson358/devise-security-email-validation

If you get that, run the DB migrate, and then rspec, you will see the error:

`# NameError:
#   uninitialized constant User::EmailValidator
#   /Users/davidhanson/.rvm/gems/ruby-2.3.1@sln/gems/activemodel-5.1.6/lib/active_model/validations/validates.rb:118:in `const_get'`

If you don't think this is part of this gem, I can try opening the ticket at devise-security.  @cdhagmann did you happen to be using devise-security as well when you encountered this error?

**Comment by micke** [comment]
@dhanson358 I see. That's a bit confusing :D

You need to add `email_validation: false`. So if you change line 4 to
```ruby
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :secure_validatable, email_validation: false
```

Then your later validation will work properly.

devise-security expects there to be a EmailValidator.

Because we were clashing with a `EmailValidator` that was shipped with devise we namespaced under `valid_email_2`.

**Comment by dhanson358** [comment]
So, in effect that is telling devise-security to ignore email validation (hence avoiding the `EmailValidator` error) and implicitly we're letting our user's email validation take it's place?  Is that right?

**Comment by micke** [comment]
@dhanson358 you are disabling devise-security implicit email validation and explicitly enabling your own here https://github.com/dhanson358/devise-security-email-validation/blob/master/app/models/user.rb#L6

**Comment by dhanson358** [comment]
Thanks for the clarification on this, seems to be working great now!

**Comment by micke** [comment]
@dhanson358 happy to hear!
