### ISSUE TITLE
Invalid email with Accented characters 

### ISSUE THREAD

**Issue by XavierMeunier** [micke/valid_email2#126]
Hi,

It seems that emails with accented characters are invalid whereas it's supposed to be valid according to international norms.

Is it planned to support ?
– Latin Alphabet (with diacritics): Pelé@example.com
– Greek Alphabet
– Japanese Characters
– Cyrillic Characters

Thanks,

Xavier

**Comment by micke** [comment]
Hi. Yeah it seems like i was a bit strict when validating domains. Prohibiting unicode and other characters that certainly are valid nowadays.
I just pushed version 3.0.1 to rubygems with this fixed :)

Thanks!
