### ISSUE TITLE
The domain id.au might not be disposable

### ISSUE THREAD

**Issue by maxim** [micke/valid_email2#131]
We got a complaint about id.au being legit (seems like just one of many possible Australian domain tld combinations), yet it's included in the list of disposable domains. It seems the an.id.au (also in the list) is intended to be marked disposable, but id.au is not. Smells like a mistake to me. Here are my findings on why it might be a mistake:

1. including an.id.au on top of id.au is redundant
2. according to a quick google, anyone can register *.id.au domains at regular registrars

Should we perhaps remove id.au from the list?

**Comment by micke** [comment]
Hi. So sorry that i haven't given you a response until now. The email must have been accidentally archived or not reached me properly.

Thanks for doing a thorough investigation into this, i've released version v3.0.3 with the tld removed from the list of disposable email providers.

Cheers!

**Comment by maxim** [comment]
No worries, we implemented a workaround locally, but happy to remove it now. 👍 Thank you for this nice lib.
