### ISSUE TITLE
Email address wrapped in single quotes should not be considered valid

### ISSUE THREAD

**Issue by jana4u** [micke/valid_email2#148]
`'test@example.com'` should **not** be valid email address
`test@example.com` should be valid email address

currently:

```
ValidEmail2::Address.new("'test@example.com'").valid?
=> true
```

tested in latest released version `valid_email2 (3.2.1)`

**Comment by micke** [comment]
Thanks for reporting the issue!
I've pushed version 3.2.2 with this fixed!
