### ISSUE TITLE
yandex.net is not a disposable mail service, please remove it from disposable domains list.

### ISSUE THREAD

**Issue by ftroitsky** [micke/valid_email2#158]
Hey, @micke. 
For some reason, you've added yandex.net to the disposable domains list.
It's a pretty much legit mail service from Yandex. It's a respectable company, at least in Russia, although with Belgian registration. It also offers services for businesses with an option to connect your domain, very much like Gmail for G-suite. Our company happens to use it with a custom domain. And to my great surprise, when someone sent me an invite to the Netlify's team account I was unable to register, and Netlify's support referred to this project.
Please consider removing it.

**Comment by micke** [comment]
Sorry for this, i've pushed 3.2.4 to rubygems!

**Comment by ftroitsky** [comment]
Thanks @micke
