### ISSUE TITLE
Dot started email marked as valid

### ISSUE THREAD

**Issue by morkevicius** [micke/valid_email2#164]
ValidEmail2::Address.new('.test@gmail.com').valid?
 => true 
ValidEmail2::Address.new('tes..t@gmail.com').valid?
 => true 

[RFC 3696](https://tools.ietf.org/html/rfc3696
)

> Without quotes, local-parts may consist of any combination of
   alphabetic characters, digits, or any of the special characters
>      ! # $ % & ' * + - / = ?  ^ _ ` . { | } ~
>   **period (".") may also appear, but may not be used to start or end the
   local part, nor may two or more consecutive periods appear**.  Stated
   differently, any ASCII graphic (printing) character other than the
   at-sign ("@"), backslash, double quote, comma, or square brackets may
   appear without quoting.  If any of that list of excluded characters
   are to appear, they must be quoted.  Forms such as

**Comment by micke** [comment]
Hi. Which version are you using?
3.4.0 validates against consecutive dots.
We do not validate that local part doesn't start or end with a dot. PR's are welcome!
