### ISSUE TITLE
Documentation: Is it possible to only blacklist only NEW users, not existing ones?

### ISSUE THREAD

**Issue by kingpalethe** [micke/valid_email2#177]
This gem looks really useful. I wish the documentation would mention something that, at least to me, seems really basic, but I can't figure out:

**How can I use this to prevent only problematic _new_ users in my rails application?**

As far as I can tell, if I install this gem, then there might be many _existing_ users in my application whose email addresses might **not** now pass validation. This is a huge can of worms that I don't want to open, because many of these _existing_ users I might want to keep. 

Did I miss something? Is there an easy to to make sure that the validation only applies to _new_ users?

I'm using a standard `User` model, like in the various Devise tutorials.

thanks

**Comment by micke** [comment]
Hi. And thank you for the kind words!

This is a general rails validation question and not something that this gem solves exclusively, as such i do not think it belongs in the documentation.

I can however point you in the right direction: https://guides.rubyonrails.org/active_record_validations.html#on
I think you can accomplish what you are looking for by passing `on: :create` to the call to `validates`
