### ISSUE TITLE
Caching of domain dns/mx check

### ISSUE THREAD

**Issue by la-ruby** [micke/valid_email2#179]
ValidEmail2::Address.new("example@ymail.con").valid_mx?  => false
    
    
the fact that ymail.con is not a valid domain, can the gem cache that fact?
during bulk checking of 1000 email addresses, that would avoid the need to make 1000 network requests.

**Comment by micke** [comment]
Great idea! A PR is most welcome!

**Comment by ianbayne** [comment]
Any thoughts on desired implementation for this, @micke? For example, a simple class-level cache using a class variable? Or something thread-safe like [`concurrent-ruby`](https://github.com/ruby-concurrency/concurrent-ruby) or `Rails.cache` (through requiring `activesupport` I guess)?
