### ISSUE TITLE
Could we set a "reasonable" timeout for dns resolution?

### ISSUE THREAD

**Issue by lostapathy** [micke/valid_email2#180]
I've noticed we occasionally get really, really slow results from `Address::valid_strict_mx?` - like 75 seconds today for tds.com.  This appears to be coming through from the dns resolution in `Address::mx_servers` taking similarly long to time out, at least on my system.

I'd like to see us set a DNS resolution timeout limit in `mx_servers` and `mx_or_a_servers` to proud a tighter bound on performance.  I'm happy to put together a PR but not sure what we think is reasonable.

Is 5 seconds too aggressive?

**Comment by micke** [comment]
Great idea!

Can we make it configurable and default it to 5 seconds? Then someone can override it if they need it to be higher
