### ISSUE TITLE
Emails with # in the domain pass as valid

### ISSUE THREAD

**Issue by zzip** [micke/valid_email2#192]
Hi,

First of all thanks for this gem, while using it we received an error message `Net::SMTPSyntaxError: 501 5.1.3 Bad recipient address syntax`. Upon closer inspection the email address contains a `#` char in the domain part.

When trying to reproduce, it seems that this passes as valid: 

```
address = ValidEmail2::Address.new("testname@#somedomain.com")
address.valid?
=> true
```

Tested with the latest version (4.0.3)

Afaik this is not what the RFC allows.

Greetings,
Dale

**Comment by micke** [comment]
Hi. Until i have time to properly investigate this you could override the regex used to validate against prohibited characters in the domain name,

```ruby
ValidEmail2::Address.prohibited_domain_characters_regex = /[+!_\/\s'`#]/
```

**Comment by micke** [comment]
Closing this as `#` in fact seem to be allowed in the local(before @) part of a email address.
