### ISSUE TITLE
spray.se is interpreted as a disposable domain, but it is not listed in the config

### ISSUE THREAD

**Issue by davidwessman** [micke/valid_email2#198]
Hello!

There is an old Swedish email provider called **spray.se** which I am not sure why anyone still use, but it is valid.

Then I checked in the list of disposable emails and I found multiple starting with `spray`, but no direct match.

**Does the disposable list not require an exact match for the domain?**

```ruby
email = "github@spray.se"
address = ValidEmail2::Address.new(email)
address.valid_mx?
# => true
address.disposable?
# => true
```

We solve it for now by adding it to our allowed domains.

**Comment by micke** [comment]
Hi!

Sorry about this, we check if both the domain itself AND the domains MX servers is in the list of disposable domains.
spray.se uses mail2world.com and that was in fact in the list of disposable domains, but I've released 4.0.5 with it remvoed.

And i agree, i don't understand why som Swedes still use Spray, it feels so early 2000 :D

Thanks for bringin this to my attention!
