### ISSUE TITLE
Remove mozmail.com from disposable email domains

### ISSUE THREAD

**Issue by jwhitlock** [micke/valid_email2#202]
I'm a developer for [Firefox Relay](https://relay.firefox.com/). Back in 2021, we took over the mozmail.com domain for our aliases. We are operating Relay with a number of features that I think mitigate the risks that these aliases pose:

* Bounces & deliver-ability - if our user disables an @mozmail.com alias, we DO NOT trigger a bounce. Instead, [we silently drop the email](https://github.com/mozilla/fx-private-relay/blob/4ccc3957076b37d9b263241e0bd727f41893ac15/emails/views.py#L406-L422).
* Anti-abuse protections - we limit our free users to 5 total aliases, and we rate-limit our premium customers so they cannot create large-scale throw-away aliases for abusive sign-ups and behaviors.

So, we'd like to have mozmail.com removed from the disposable email domains list, please.

**Comment by micke** [comment]
I'm really sorry for not attending to this earlier.

My only concern is that the firefox relay can be considered a throw-away email provider even with the features you described. Is it possible for you to elaborate on how firefox relay isn't a throw-away email provider. It isn't really clear from the website, especially for premium accounts.

**Comment by jwhitlock** [comment]
I don't see a definition on this repo of a throw-away email provider, so I'll describe the service and maybe you can tell me which way it leans. 

We're providing a service similar to Apple's "Hide my email" service, but through our Firefox Accounts system.

A user signs up by creating a Firefox Account, which includes verifying their email address by entering the code sent to that address. A user can then generate an `@mozmail.com` email address and provide it to the website. All emails sent to that address are forwarded to their verified Firefox Account email, and they can respond to the email to start a conversation, without exposing their "true" email to the website. A free user gets 5 random emails, and a premium user (paying monthly or yearly) has unlimited random emails as well as a catch-all domain email `@some-subdomain.mozmail.com`, so they can generate emails on the go, like `some-store@some-subdomain.mozmail.com`.

Some users use the service so that the website isn't able to look up personal information linked to their email. Others use an email per website so that they have a defense if a website's database is breached. Others may use it to get around one-account-per-email restriction, similar to subaddress extensions.

Once you have a random email, you can delete it, and that random email will not be reused. You can also set it to block all emails. It's a little like email filters.

**Comment by micke** [comment]
Thank you for the explanation!

The paywall in the service which prevents free users from creating more than 5 aliases is great, but if it's possible to delete the aliases and essentially use more than 5 aliases i would still see it as a disposable email provider.

Despite this, i've merged your PR and we will wait and see if someone raises a issue or creates a PR to add mozmail back!

Users of the gem can still add mozmail in their local block list to override this decision.

**Comment by micke** [comment]
I've released version 5.0.2 where mozmail is removed!
