### ISSUE TITLE
Remove SimpleLogin domains from disposable email domains

### ISSUE THREAD

**Issue by nguyenkims** [micke/valid_email2#211]
I'm a developer behind [SimpleLogin](https://simplelogin.io/). It's an open source email alias service that aims to protect a mailbox against spams and phishing.

An email alias isn't a disposable email address as it's permanent.

SimpleLogin has a robust anti abuse system to avoid malicious users from using our service for bulk sign up or for sending unwanted emails.

For these reasons, I'd like to remove our domains from your list. Below are the domains we're currently using:

simplelogin.com
simplelogin.fr
simplelogin.co
simplelogin.io
aleeas.com
slmails.com
silomails.com
slmail.me

Thanks a lot!

Bounces & deliver-ability - if our user disables an @mozmail.com alias, we DO NOT trigger a bounce. Instead, [we silently drop the email](https://github.com/mozilla/fx-private-relay/blob/4ccc3957076b37d9b263241e0bd727f41893ac15/emails/views.py#L406-L422).
Anti-abuse protections - we limit our free users to 5 total aliases, and we rate-limit our premium customers so they cannot create large-scale throw-away aliases for abusive sign-ups and behaviors.
So, we'd like to have mozmail.com removed from the disposable email domains list, please.

**Comment by bermudi** [comment]
Hello, 

I'm an end user and the person who asked SimpleLogin developers to open an issue here. 

I want to clarify a few things. I am using SimpleLogin to handle email on my own domains. I am not using the domains provided by SimpleLogin and I'm still having issues in some places when creating an account with my own domain and being flagged as "disposable address". Apparently this repo is also doing some MX records lookup and flagging unlisted domains based on that.

**Comment by piouPiouM** [comment]
Hi, SimpleLogin's user here :wave:

I've just encountered this issue when I tried to create a Netlify account, which I'm [not allowed to do](https://answers.netlify.com/t/unable-to-create-user-account-using-custom-email-domain/82167/4) because of MX record validation. SimpleLogin lets me manage my own domain and keep my real email address safe :muscle:

**Comment by bermudi** [comment]
> Hi, SimpleLogin's user here 👋
> 
> I've just encountered this issue when I tried to create a Netlify account, which I'm [not allowed to do](https://answers.netlify.com/t/unable-to-create-user-account-using-custom-email-domain/82167/4) because of MX record validation. SimpleLogin lets me manage my own domain and keep my real email address safe 💪

I came up with a temp fix but I'm still waiting for Proton/SimpleLogin to comment 
https://www.reddit.com/r/ProtonPass/comments/16r5giv/how_will_proton_deal_with_simplelogin_being/k21yfw9/

**Comment by micke** [comment]
Pull request is really welcomed!

**Comment by micke** [comment]
Version 5.0.4 released with some of them removed?

**Comment by micke** [comment]
Looks like you guys removed all of them, i've added them to the ignore list so that they won't be imported from other lists.
