### ISSUE TITLE
Add mozmail.com to ignore list

### ISSUE THREAD

**Issue by ghost** [micke/valid_email2#219]
Hi!

You already removed mozmail.com, but it would be nice if you will add it to ignore list

https://github.com/micke/valid_email2/commit/f40320edd37b884692c874e5cd61d110992e19ce

**Comment by Piker68** [comment]
@micke take a look

**Comment by micke** [comment]
Fixed in https://github.com/micke/valid_email2/commit/d861f3de56bceb53d537306f88c9cf26d665c0f5
