### ISSUE TITLE
Remove SimpleLogin domains from disposable email domains 

### ISSUE THREAD

**Issue by Nikola-Test-for-Proton** [micke/valid_email2#223]
Hi, this is Nikola. 

Just continuing off from where [this issue](https://github.com/micke/valid_email2/issues/211) was closed. 

I work in Proton's (and SimpleLogin's) Anti-Abuse team and noticed that not all of the domains have been removed from your list of disposable emails. To be more precise, dralias.com and 8shield.net are still included. 

We would appreciate it if you could look into this for us accordingly.

Your patience and understanding are greatly appreciated.

**Comment by micke** [comment]
Pull requests are welcome!

**Comment by acasajus** [comment]
Hello, I've made an MR #224 to remove them

**Comment by micke** [comment]
I've released version 5.1.1
