### ISSUE TITLE
Remove addy.io domains and add them to the ignore list

### ISSUE THREAD

**Issue by pardub** [micke/valid_email2#226]
Hi,
Could you please remove addy.io domains and add them to the ignore list ?
It's a similar service as Simplelogin.
Thanks

**Comment by Hvhxgcitx** [comment]
No it is not. It doesn’t provide any ability to reply for incoming messages and has a bootstrap limit. So technically it is halfly disposable (because in half situations user can NOT change service behaviour to reject mails).

**Comment by Ugnkgyckif** [comment]
![IMG_1502](https://github.com/micke/valid_email2/assets/153685976/e100381d-c544-4560-92e5-f9ce577a2e52)

**Comment by micke** [comment]
Thanks! I've release v5.2.2!
