### ISSUE TITLE
Add maskmy.id disposable domain

### ISSUE THREAD

**Issue by ghost** [micke/valid_email2#229]
Provider is https://skiff.com/quick-alias and it's actually subdomains, each user can generate their own subdomain. I tested it, very easy.

The page title of https://skiff.com/quick-alias is "Quick alias burner email address". In the HTML I see

```
<meta name="description" content="Secure and quick-to-create burner email addresses with Skiff!
```

There is a browser plugin https://github.com/irazasyed/email-masker to create one email per website, skiff.com's twitter account promoted it, the github repository is tagged as 'burner-email'

You should add:

- `maskmy.id` because it is there main domain
- `anything.maskmy.id` because it allows you to create disposable addresses with random subdomains

![IMG_1500](https://github.com/micke/valid_email2/assets/153685976/c7772fee-7c6c-4871-9f42-ea3a6a18fbed)
![IMG_1501](https://github.com/micke/valid_email2/assets/153685976/b5b94c72-c595-460d-b92f-a358fe112b17)

**Comment by Ugnkgyckif** [comment]
@micke

**Comment by Hchchg** [comment]
Also 

**
mailbox.zip
sailmail.io
**

They added new domain
![IMG_1719](https://github.com/micke/valid_email2/assets/155533164/eea70a19-e505-48c2-adf3-9aca6306fc5e)

**Comment by micke** [comment]
Thanks! I've release v5.2.2!
