### ISSUE TITLE
All "my.id" and "web.id" are blocked.

### ISSUE THREAD

**Issue by bayuah** [micke/valid_email2#240]
It seems all domain with suffix `my.id` and `web.id` as blocked as "disposable_email_domains.txt" say. Both are domain that for personal use in Indonesia.

I personally use `web.id` for my email domain **NOT** for disposable purpose.  Also for `web.id` need national residential ID for registration, so this is somewhat secure.

Why both there and is this possible to remove both as it will trigger false positive?

Thank you.

**Further reading:** https://en.wikipedia.org/wiki/.id

**Comment by micke** [comment]
Sorry about that and thanks for reporting it!

I've pushed 5.2.5 to rubygems with `my.id` and `web.id` removed!

**Comment by bayuah** [comment]
@micke: Thank you so much. I was unable automatically registered in some services (maybe) because of it. I was resolve with contact the support center. I was troublesome, and make me reluctant to use them. Once again, thank you.
