### ISSUE TITLE
Checking MX to simplify disposable_emails.yml?

### ISSUE THREAD

**Issue by scouttyg** [micke/valid_email2#95]
Keeping a "disposable email" blocklist becomes harder and harder as time goes on, as more and more domains are added to the list, become expired, need to be removed, etc.

Instead, could we check MX records and look for common providers? 

For example, if we look at `sogetthis.com` (an entry in `disposable_emails.yml`) mx records we get:

```bash
;; ANSWER SECTION:
sogetthis.com.		86400	IN	MX	10 mail.mailinator.com.
```

It's an MX Record that points to `mailinator.com` (as I'm sure a good other amount of the domains do)

Similarly, let's take a look at something like `inclusiveprogress.com` (also an entry in `disposable_emails.yml`):

```bash
;; ANSWER SECTION:
inclusiveprogress.com.	3600	IN	MX	0 mx3.mytemp.email.
inclusiveprogress.com.	3600	IN	MX	0 mx1.mytemp.email.
inclusiveprogress.com.	3600	IN	MX	0 mx2.mytemp.email.
```

It's an MX Record to `mytemp.email, which again I'm sure is not the only email in our list to do so.

If we instead had a separate yml file for something like "MX Record domains" , we could vastly simplify what we have to add/remove to `disposable_emails.yml` -- only domains that didn't take the "simple" approach of just pointing their mx records to a well known disposable email provider.

*The upsides:* Could vastly simplify our disposable email list, and could help block spam websites we haven't perfectly defined if they use the common MX forwarding trick.

*The downsides:* Same as the downsides to checking mx records (we need an internet connection to get the MX records).

**Comment by lisinge** [comment]
Hi Scott.

Thanks for a such well put together Feature Request! This is a great idea! I haven't though of this before but it should at least make it easier to block all of a providers domains, even new and unknown ones.

Unfortunately i don't really have the possibility of implementing this right now, but i would gladly review and merge a PR if you have the possibility of putting one together.

*PS.* a good name might be `providers_email_servers.yml`?

**Comment by micke** [comment]
@scouttyg I've just pushed version v3 of this gem with your proposed feature. Read more here https://github.com/micke/valid_email2/blob/master/CHANGELOG.md#version-300
